version: '3'

services:
   api:
      build: 
         context: .
         dockerfile: Dockerfile.api
      container_name: flickr-photo-grid-api
      ports:
         - 8000:8000
      links: 
        - redis
        
   web:
      build: 
         context: .
         dockerfile: Dockerfile.web
      container_name: flickr-photo-grid-web
      ports:
         - 3000:3000
      links: 
        - api
    
   redis:
      image: redis
      container_name: redis
      ports:
        - 6379:6379
      volumes: 
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      command: redis-server /usr/local/etc/redis/redis.conf
